name: flipperkit_dio_interceptor
description: flipperkit_dio_interceptor
version: 0.0.3
author: JianyingLi <lijy91@foxmail.com>
homepage: https://github.com/blankapp/flutter_flipperkit_plugins

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  flutter_flipperkit: ^0.0.23
  uuid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
