name: flipperkit_redux_middleware
description: flipperkit_redux_middleware
version: 0.0.3
author: JianyingLi <lijy91@foxmail.com>
homepage: https://github.com/blankapp/flutter_flipperkit_plugins

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flipperkit: ^0.0.10
  redux: ^4.0.0
  uuid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
