name: flipperkit_redux_middleware
description: flipperkit_redux_middleware
version: 0.0.4
author: JianyingLi <lijy91@foxmail.com>
homepage: https://github.com/blankapp/flutter_flipperkit_plugins

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flipperkit:
    git:
      url: git://github.com/prtm/flutter_flipperkit.git
      ref: master
  redux: any
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

